name: SO-Project-Final-Fix

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build Java Module
        run: javac HileModul.java

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      # LNK2019 Hatasının çözümü: jvm.lib yolu ve dosyası eklendi
      - name: Build C++ DLL
        shell: cmd
        run: |
          cl.exe /LD dllmain.cpp /I"%JAVA_HOME%\include" /I"%JAVA_HOME%\include\win32" /link /LIBPATH:"%JAVA_HOME%\lib" jvm.lib /OUT:cheat.dll

      - name: Build Injector
        run: cl.exe main.cpp /FE:Injector.exe /EHsc

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SO-Cheat-Package
          path: |
            cheat.dll
            HileModul.class
            Injector.exe
            
